<Project>
  <PropertyGroup>
    <ArisenEngineRoot>$(MSBuildThisFileDirectory)</ArisenEngineRoot>
    
    <!-- Core Projects -->
    <ArisenEngineProject>$(ArisenEngineRoot)Engine\ArisenEngine.csproj</ArisenEngineProject>
    <AutoBindingProject>$(ArisenEngineRoot)AutoBinding\AutoBinding.csproj</AutoBindingProject>
    <ArisenDAGProject>$(ArisenEngineRoot)External\ArisenDAG\ArisenDAG.csproj</ArisenDAGProject>
    <BindingGeneratorProject>$(ArisenEngineRoot)BindingGenerator\BindingGenerator.csproj</BindingGeneratorProject>

  </PropertyGroup>
</Project>
