// ----------------------------------------------------------------------------
// <auto-generated>
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
// </auto-generated>
// ----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;
using __CallingConvention = global::System.Runtime.InteropServices.CallingConvention;
using __IntPtr = global::System.IntPtr;

#pragma warning disable CS0109 // Member does not hide an inherited member; new keyword is not required

namespace ArisenEngine
{
    namespace Platforms
    {
        public unsafe partial class Platform
        {
            public partial struct __Internal
            {
                [SuppressUnmanagedCodeSecurity, DllImport("Core.Platform.dll", EntryPoint = "?CreateNewWindow@Platforms@ArisenEngine@@YA?AVWindow@12@QEBUWindowInitInfo@12@@Z", CallingConvention = __CallingConvention.Cdecl)]
                internal static extern void CreateNewWindow(__IntPtr @return, __IntPtr initInfo);

                [SuppressUnmanagedCodeSecurity, DllImport("Core.Platform.dll", EntryPoint = "?GetWindowID@Platforms@ArisenEngine@@YAIPEAUHWND__@@@Z", CallingConvention = __CallingConvention.Cdecl)]
                internal static extern uint GetWindowID(global::System.IntPtr handle);

                [SuppressUnmanagedCodeSecurity, DllImport("Core.Platform.dll", EntryPoint = "?RemoveWindow@Platforms@ArisenEngine@@YAXI@Z", CallingConvention = __CallingConvention.Cdecl)]
                internal static extern void RemoveWindow(uint id);

                [SuppressUnmanagedCodeSecurity, DllImport("Core.Platform.dll", EntryPoint = "?SetWindowResizeCallbackInternal@Platforms@ArisenEngine@@YAXIP6AXPEAUHWND__@@II@Z@Z", CallingConvention = __CallingConvention.Cdecl)]
                internal static extern void SetWindowResizeCallbackInternal(uint id, __IntPtr callback);
            }

            public static global::ArisenEngine.Platforms.Window CreateNewWindow(global::ArisenEngine.Platforms.WindowInitInfo initInfo)
            {
                var __arg0 = initInfo is null ? __IntPtr.Zero : initInfo.__Instance;
                var ___ret = new global::ArisenEngine.Platforms.Window.__Internal();
                __Internal.CreateNewWindow(new IntPtr(&___ret), __arg0);
                return global::ArisenEngine.Platforms.Window.__CreateInstance(___ret);
            }

            public static uint GetWindowID(global::System.IntPtr handle)
            {
                var ___ret = __Internal.GetWindowID(handle);
                return ___ret;
            }

            public static void RemoveWindow(uint id)
            {
                __Internal.RemoveWindow(id);
            }

            public static void SetWindowResizeCallbackInternal(uint id, __IntPtr callback)
            {
                __Internal.SetWindowResizeCallbackInternal(id, callback);
            }
        }
    }
}
