#pragma once
#include "RHITypes.h"


ARISENRHI_BEGIN_NAMEPSACE
enum class D3D12_VALIDATION_FLAGS : uint8_t
{
    D3D12_VALIDATION_FLAG_NONE = 0x00,
    D3D12_VALIDATION_FLAG_GPU_BASED_VALIDATION = 0x01,
};


struct EngineCreateInfoD3D12 : public ArisenRHI::EngineCreateInfo
{
    D3D12_VALIDATION_FLAGS ValidationFlags {D3D12_VALIDATION_FLAGS::D3D12_VALIDATION_FLAG_NONE};
};

ARISENRHI_END_NAMESPACE
