<?xml version='1.0' encoding='utf-8'?>
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>BindingGenerator</AssemblyName>
        <RootNamespace>BindingGenerator</RootNamespace>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath></PropertyGroup>
<PropertyGroup>
  <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
</PropertyGroup>
    <ItemGroup>
      <PackageReference Include="CppSharp" Version="1.1.5.3168" />
    </ItemGroup>
    <ItemGroup>
      <Folder Include="Src\" />
    </ItemGroup>

<PropertyGroup Condition="'$(Configuration)' == 'Debug'">
<OutputPath>..\Projects\VisualStudio\ArisenEngineTest\Outputs\Debug\</OutputPath>
</PropertyGroup>
<PropertyGroup Condition="'$(Configuration)' == 'Release'">
<OutputPath>..\Projects\VisualStudio\ArisenEngineTest\Outputs\Release\</OutputPath>
</PropertyGroup>
</Project>