#pragma once

namespace ArisenEngine::RHI
{
    typedef enum AttachmentStoreOp {
        ATTACHMENT_STORE_OP_STORE = 0,
        ATTACHMENT_STORE_OP_DONT_CARE = 1,
        ATTACHMENT_STORE_OP_NONE = 1000301000,
        ATTACHMENT_STORE_OP_NONE_KHR = ATTACHMENT_STORE_OP_NONE,
        ATTACHMENT_STORE_OP_NONE_QCOM = ATTACHMENT_STORE_OP_NONE,
        ATTACHMENT_STORE_OP_NONE_EXT = ATTACHMENT_STORE_OP_NONE,
        ATTACHMENT_STORE_OP_MAX_ENUM = 0x7FFFFFFF
    } AttachmentStoreOp;
}
