// ----------------------------------------------------------------------------
// <auto-generated>
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
// </auto-generated>
// ----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;
using __CallingConvention = global::System.Runtime.InteropServices.CallingConvention;
using __IntPtr = global::System.IntPtr;

#pragma warning disable CS0109 // Member does not hide an inherited member; new keyword is not required

namespace NebulaEngine
{
    namespace Platforms
    {
        public unsafe partial class Platform
        {
            public partial struct __Internal
            {
                [SuppressUnmanagedCodeSecurity, DllImport("Core.Platform.dll", EntryPoint = "?CreateNewWindow@Platforms@NebulaEngine@@YA?AVWindow@12@QEBUWindowInitInfo@12@@Z", CallingConvention = __CallingConvention.Cdecl)]
                internal static extern void CreateNewWindow(__IntPtr @return, __IntPtr initInfo);

                [SuppressUnmanagedCodeSecurity, DllImport("Core.Platform.dll", EntryPoint = "?RemoveWindow@Platforms@NebulaEngine@@YAXI@Z", CallingConvention = __CallingConvention.Cdecl)]
                internal static extern void RemoveWindow(uint id);
            }

            public static global::NebulaEngine.Platforms.Window CreateNewWindow(global::NebulaEngine.Platforms.WindowInitInfo initInfo)
            {
                var __arg0 = initInfo is null ? __IntPtr.Zero : initInfo.__Instance;
                var ___ret = new global::NebulaEngine.Platforms.Window.__Internal();
                __Internal.CreateNewWindow(new IntPtr(&___ret), __arg0);
                return global::NebulaEngine.Platforms.Window.__CreateInstance(___ret);
            }

            public static void RemoveWindow(uint id)
            {
                __Internal.RemoveWindow(id);
            }
        }
    }
}
