// ----------------------------------------------------------------------------
// <auto-generated>
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
// </auto-generated>
// ----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;
using __CallingConvention = global::System.Runtime.InteropServices.CallingConvention;
using __IntPtr = global::System.IntPtr;

#pragma warning disable CS0109 // Member does not hide an inherited member; new keyword is not required

namespace NebulaEngine
{
    public unsafe partial class PrimitiveTypes
    {
        public partial struct __Internal
        {
        }

        public const ulong U64Invalid = 18446744073709551615;
        public const uint U32Invalid = 4294967295;
        public const ushort U16Invalid = 65535;
        public const byte U8Invalid = 255;
        public const uint InvalidID = 4294967295;    }
}
