// ----------------------------------------------------------------------------
// <auto-generated>
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
// </auto-generated>
// ----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;
using __CallingConvention = global::System.Runtime.InteropServices.CallingConvention;
using __IntPtr = global::System.IntPtr;

#pragma warning disable CS0109 // Member does not hide an inherited member; new keyword is not required

namespace NebulaEngine
{
    namespace Platforms
    {
        public unsafe partial class RenderWindowAPI
        {
            public partial struct __Internal
            {
                [SuppressUnmanagedCodeSecurity, DllImport("Core.Platform.dll", EntryPoint = "RemoveRenderSurface", CallingConvention = __CallingConvention.Cdecl)]
                internal static extern void RemoveRenderSurface(uint id);

                [SuppressUnmanagedCodeSecurity, DllImport("Core.Platform.dll", EntryPoint = "ResizeRenderSurface", CallingConvention = __CallingConvention.Cdecl)]
                internal static extern void ResizeRenderSurface(uint id, uint width, uint height);

                [SuppressUnmanagedCodeSecurity, DllImport("Core.Platform.dll", EntryPoint = "GetWindowWidth", CallingConvention = __CallingConvention.Cdecl)]
                internal static extern uint GetWindowWidth(uint id);

                [SuppressUnmanagedCodeSecurity, DllImport("Core.Platform.dll", EntryPoint = "GetWindowHeight", CallingConvention = __CallingConvention.Cdecl)]
                internal static extern uint GetWindowHeight(uint id);
            }

            public static void RemoveRenderSurface(uint id)
            {
                __Internal.RemoveRenderSurface(id);
            }

            public static void ResizeRenderSurface(uint id, uint width, uint height)
            {
                __Internal.ResizeRenderSurface(id, width, height);
            }

            public static uint GetWindowWidth(uint id)
            {
                var ___ret = __Internal.GetWindowWidth(id);
                return ___ret;
            }

            public static uint GetWindowHeight(uint id)
            {
                var ___ret = __Internal.GetWindowHeight(id);
                return ___ret;
            }
        }
    }
}
