<?xml version='1.0' encoding='utf-8'?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	 
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <BaseOutputPath>..\..\x64\</BaseOutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
	<PlatformTarget>x64</PlatformTarget>
	<RootNamespace>ArisenEngine</RootNamespace>
	<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\AutoBinding\AutoBinding.csproj" />
    <ProjectReference Include="..\..\Serialization\Serialization\Serialization.csproj" />
  </ItemGroup>
<PropertyGroup>
  <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
</PropertyGroup>
  <ItemGroup>
    <Folder Include="Platforms\Android\" />
    <Folder Include="Platforms\IOS\" />
    <Folder Include="Platforms\PS5\" />
    <Folder Include="Platforms\Switch\" />
    <Folder Include="Platforms\XBox\" />
    <Folder Include="Serialization\Meta\" />
    <Folder Include="Hook\" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ArisenEditor" />
    <InternalsVisibleTo Include="ArisenEditor.Desktop" />
  </ItemGroup>

  
  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>ArisenEditor</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
</Project>