using System;
using ArisenBinding.NativeCore;

namespace ArisenEngine;

public static class Bootstrap
{
    private static bool m_IsInitialized = false;

    public static bool Initialize()
    {
        if (m_IsInitialized) return true;

        try
        {
            // Call native EngineInit::Initialize
            // Note: ArisenBinding.NativeCore.EngineInit is generated by CppSharp
            if (EngineInit.Initialize())
            {
                m_IsInitialized = true;
                return true;
            }
        }
        catch (Exception e)
        {
            Console.WriteLine($"[Bootstrap] Failed to initialize native engine: {e.Message}");
        }

        return false;
    }

    public static void Shutdown()
    {
        if (!m_IsInitialized) return;

        try
        {
            EngineInit.Shutdown();
            m_IsInitialized = false;
        }
        catch (Exception e)
        {
            Console.WriteLine($"[Bootstrap] Error during native engine shutdown: {e.Message}");
        }
    }
}
