using System.Collections.Generic;
using System.IO;
using System.Text;
using BindingGenerator.Models;
using BindingGenerator.Parser;
using BindingGenerator.Utils;

namespace BindingGenerator.Generator;

public static class CSharpGenerator
{
    public static List<(string PackageId, string FileName, string Content, string SubDir)> ProcessHeader(string content,
        string headerPath, string generationTime)
    {
        var results = new List<(string, string, string, string)>();

        // Extract module-level metadata
        var packageId = StringUtils.ExtractMacroArg(content, "ARISEN_BIND_PACKAGE") ?? "default";
        var dllName = StringUtils.ExtractMacroArg(content, "ARISEN_BIND_MODULE") ?? "";
        var csNamespace = StringUtils.ExtractMacroArg(content, "ARISEN_BIND_NAMESPACE") ?? "";

        // --- Bridge Blocks (Phase 3) ---
        // Bridges have their own metadata in the BEGIN_BRIDGE macro
        var bridgeBlocks = BindingParser.ParseBridgeBlocks(content);

        // If csNamespace is empty but we have bridge blocks, use the namespace from the first block
        if (string.IsNullOrEmpty(csNamespace) && bridgeBlocks.Count > 0)
        {
            csNamespace = bridgeBlocks[0].Namespace;
        }

        // If neither module metadata nor bridge blocks are found, check if we have a namespace for enums/structs
        if (string.IsNullOrEmpty(dllName) && bridgeBlocks.Count == 0 && string.IsNullOrEmpty(csNamespace))
            return results;

        var subDir = !string.IsNullOrEmpty(csNamespace) ? GetSubDirFromNamespace(csNamespace) : "";

        // --- Enums ---
        if (!string.IsNullOrEmpty(csNamespace))
        {
            var enums = BindingParser.ParseEnums(content);
            foreach (var e in enums)
            {
                var sb = new StringBuilder();
                sb.AppendLine($"// Auto-generated by Arisen BindingGenerator  — DO NOT EDIT");
                sb.AppendLine();
                sb.AppendLine($"namespace {csNamespace}");
                sb.AppendLine("{");
                sb.AppendLine($"    public enum {e.Name} : {TypeMapper.MapEnumBaseType(e.BaseType)}");
                sb.AppendLine("    {");
                foreach (var (name, value) in e.Values)
                {
                    if (value != null)
                        sb.AppendLine($"        {name} = {value},");
                    else
                        sb.AppendLine($"        {name},");
                }

                sb.AppendLine("    }");
                sb.AppendLine("}");

                results.Add((packageId, $"{e.Name}.cs", sb.ToString(), subDir));
            }

            // --- Structs ---
            var structs = BindingParser.ParseStructs(content);
            foreach (var s in structs)
            {
                var sb = new StringBuilder();
                sb.AppendLine($"// Auto-generated by Arisen BindingGenerator  — DO NOT EDIT");
                sb.AppendLine("using System;");
                sb.AppendLine("using System.Runtime.InteropServices;");
                sb.AppendLine();
                sb.AppendLine($"namespace {csNamespace}");
                sb.AppendLine("{");
                sb.AppendLine("    [StructLayout(LayoutKind.Sequential)]");
                sb.AppendLine($"    public struct {s.Name}");
                sb.AppendLine("    {");
                foreach (var (type, name) in s.Fields)
                {
                    var csType = TypeMapper.MapType(type);
                    var csName = StringUtils.ToPascalCase(name);
                    sb.AppendLine($"        public {csType} {csName};");
                }

                sb.AppendLine("    }");
                sb.AppendLine("}");

                results.Add((packageId, $"{s.Name}.cs", sb.ToString(), subDir));
            }

            // --- Handles ---
            var handles = BindingParser.ParseHandles(content);
            if (handles.Count > 0)
            {
                var sb = new StringBuilder();
                sb.AppendLine($"// Auto-generated by Arisen BindingGenerator  — DO NOT EDIT");
                sb.AppendLine("using System;");
                sb.AppendLine("using System.Runtime.InteropServices;");
                sb.AppendLine();
                sb.AppendLine($"namespace {csNamespace}");
                sb.AppendLine("{");

                foreach (var handleName in handles)
                {
                    sb.AppendLine("    [StructLayout(LayoutKind.Sequential)]");
                    sb.AppendLine($"    public struct {handleName}");
                    sb.AppendLine("    {");
                    sb.AppendLine("        public uint Index;");
                    sb.AppendLine("        public uint Generation;");
                    sb.AppendLine("        public bool IsValid => Index != 0xFFFFFFFFu;");
                    sb.AppendLine(
                        $"        public static readonly {handleName} Invalid = new {handleName} {{ Index = 0xFFFFFFFF, Generation = 0 }};");
                    sb.AppendLine("    }");
                    sb.AppendLine();
                }

                sb.AppendLine("}");
                results.Add((packageId, "RHIHandle.cs", sb.ToString(), subDir));
            }
        }

        // --- Extern "C" functions ---
        var externFuncs = BindingParser.ParseExternCFunctions(content);

        if (bridgeBlocks.Count > 0)
        {
            foreach (var block in bridgeBlocks)
            {
                var blockSubDir = GetSubDirFromNamespace(block.Namespace);

                // --- P/Invoke API class (internal) ---
                var sb = new StringBuilder();
                sb.AppendLine($"// Auto-generated by Arisen BindingGenerator  — DO NOT EDIT");
                sb.AppendLine("using System;");
                sb.AppendLine("using System.Runtime.InteropServices;");
                sb.AppendLine("using System.Security;");
                sb.AppendLine();
                sb.AppendLine($"namespace {block.Namespace}");
                sb.AppendLine("{");
                if (block.Namespace == "Arisen.Native.ShaderCompiler")
                {
                    sb.AppendLine("    using Arisen.Native.RHI;");
                }
                sb.AppendLine();
                sb.AppendLine($"    public static class {block.ClassName}API");
                sb.AppendLine("    {");
                sb.AppendLine($"        private const string DllName = \"{block.DllName}\";");
                sb.AppendLine();

                foreach (var func in block.Functions)
                {
                    EmitPInvokeFunction(sb, func, "DllName");
                }

                sb.AppendLine("    }");
                sb.AppendLine("}");

                results.Add((packageId, $"{block.ClassName}API.cs", sb.ToString(), blockSubDir));

                // --- OOP Wrapper class ---
                var wrapperContent = EmitOopWrapper(block);
                if (!string.IsNullOrEmpty(wrapperContent))
                {
                    results.Add((packageId, $"{block.ClassName}.cs", wrapperContent, blockSubDir));
                }
            }
        }
        else if (externFuncs.Count > 0)
        {
            // Standalone extern "C" functions (like RenderWindowAPI)
            var className = Path.GetFileNameWithoutExtension(headerPath);
            var sb = new StringBuilder();
            sb.AppendLine($"// Auto-generated by Arisen BindingGenerator  — DO NOT EDIT");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Runtime.InteropServices;");
            sb.AppendLine("using System.Security;");
            sb.AppendLine();
            sb.AppendLine($"namespace {csNamespace}");
            sb.AppendLine("{");
            if (csNamespace == "Arisen.Native.ShaderCompiler" || csNamespace == "Arisen.Native.RHI" || csNamespace == "")
            {
                sb.AppendLine("    using Arisen.Native.RHI;");
            }
            sb.AppendLine();
            sb.AppendLine($"    public static class {className}");
            sb.AppendLine("    {");
            sb.AppendLine($"        private const string DllName = \"{dllName}\";");
            sb.AppendLine();

            foreach (var func in externFuncs)
            {
                EmitPInvokeFunction(sb, func, "DllName");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            results.Add((packageId, $"{className}.cs", sb.ToString(), subDir));
        }

        return results;
    }

    /// <summary>Compute subdirectory from namespace (e.g. "Arisen.Native.RHI" → "RHI").</summary>
    public static string GetSubDirFromNamespace(string csNamespace)
    {
        // "Arisen.Native.HAL" → root (backward compat)
        // "Arisen.Native.RHI" → "RHI"
        // "Arisen.Native.ShaderCompiler" → root (backward compat for existing files)
        var parts = csNamespace.Split('.');
        if (parts.Length >= 3)
        {
            var last = parts[^1];
            if (last == "HAL" || last == "ShaderCompiler")
                return ""; // keep at root for backward compatibility
            return last;
        }

        return "";
    }

    private static void EmitPInvokeFunction(StringBuilder sb, FunctionInfo func, string dllConst)
    {
        var csReturnType = TypeMapper.MapType(func.ReturnType);
        var csParams = new List<string>();

        foreach (var (type, name) in func.Parameters)
        {
            var csType = TypeMapper.MapType(type);
            var marshalAttr = TypeMapper.GetMarshalAttribute(type);
            if (!string.IsNullOrEmpty(marshalAttr))
                csParams.Add($"{marshalAttr} {csType} {name}");
            else
                csParams.Add($"{csType} {name}");
        }

        sb.AppendLine(
            $"        [SuppressUnmanagedCodeSecurity, DllImport({dllConst}, CallingConvention = CallingConvention.Cdecl)]");
        sb.AppendLine($"        public static extern {csReturnType} {func.Name}({string.Join(", ", csParams)});");
        sb.AppendLine();
    }

    private static string? EmitOopWrapper(BridgeBlock block)
    {
        // Object-oriented wrapper generator (stub for now, as requested in Phase 3)
        // Returning null will skip generating the wrapper .cs file but allow the static API to work.
        return null;
    }
}