using System;
using System.IO;

namespace BindingGenerator.Generator;

public static class MarshallerGenerator
{
    public static void GenerateMarshaller(string outputDir, string generationTime)
    {
        var path = Path.Combine(outputDir, "UTF8Marshaller.cs");
        var content = "// Auto-generated by Arisen BindingGenerator "  + @" — DO NOT EDIT
using System;
using System.Runtime.InteropServices;
using System.Text;

namespace Arisen.Native
{
    internal static class UTF8Marshaller
    {
        public static string NativeToUTF8(IntPtr nativePtr)
        {
            if (nativePtr == IntPtr.Zero) return string.Empty;
            return Marshal.PtrToStringUTF8(nativePtr) ?? string.Empty;
        }

        public static unsafe string NativeToUTF8(IntPtr* nativePtr)
        {
            if (nativePtr == null || *nativePtr == IntPtr.Zero) return string.Empty;
            return Marshal.PtrToStringUTF8(*nativePtr) ?? string.Empty;
        }

        public static IntPtr UTF8ToNative(string str)
        {
            if (str == null) return IntPtr.Zero;
            byte[] bytes = Encoding.UTF8.GetBytes(str);
            IntPtr ptr = Marshal.AllocHGlobal(bytes.Length + 1);
            Marshal.Copy(bytes, 0, ptr, bytes.Length);
            Marshal.WriteByte(ptr, bytes.Length, 0);
            return ptr;
        }
    }
}
";
        File.WriteAllText(path, content);
        Console.WriteLine("Generated UTF8Marshaller.cs");
    }
}