using CppSharp;
using CppSharp.AST;
using CppSharp.Generators;

namespace CSharpBindingGenerator;

public class EngineLibrary : ILibrary
{
    #region Setup


    void SetupDebuggerModule(DriverOptions options)
    {
        options.OutputDir = @"../../../../AutoGenerated\Debugger\";
        var module = options.AddModule("Core.Debugger");
        module.OutputNamespace = "";
        // Core.Debugger
        module.IncludeDirs.AddRange(new string[]
        {
            @"../../../../Core\Core.Infra\",
            @"../../../../Core\Core.Debugger\",
            @"../../../../Engine\Engine\",
        });  
        
        module.Defines.AddRange(new string[]
        {
        });
        
        module.Headers.AddRange(new string[]
        {
            @"CoreDebuggerCommon.h",
            @"Logger\Logger.h",
            @"EngineCommon.h",
           
        });
        
        // lib
        module.LibraryDirs.AddRange(new string[]
        {
            @"../../../../x64\Debug"
        });
        
        module.Libraries.AddRange(new string[]
        {
            @"Core.Debugger.lib",
            @"Engine.lib"
        });
    }
    
    public void Setup(Driver driver)
    {
        var options = driver.Options;
        options.GeneratorKind = GeneratorKind.CSharp;
        SetupDebuggerModule(options);
    }

    #endregion
    
    public void Preprocess(Driver driver, ASTContext ctx)
    {
        // throw new NotImplementedException();
    }

    public void Postprocess(Driver driver, ASTContext ctx)
    {
        // throw new NotImplementedException();
    }
    
    public void SetupPasses(Driver driver)
    {
        // throw new NotImplementedException();
    }
}