using CppSharp;
using CppSharp.AST;
using CppSharp.Generators;

namespace CSharpBindingGenerator;

public class EngineLibrary : ILibrary
{
    #region Setup


    void SetupDebuggerModule(DriverOptions options)
    {
        options.OutputDir = @"D:\EngineSource\Nebula\Engine\Nebula\AutoGenerated\Debugger\";
        var module = options.AddModule("Logger");
        module.OutputNamespace = "";
        // Core.Debugger
        module.IncludeDirs.AddRange(new string[]
        {
            @"D:\EngineSource\Nebula\Engine\Nebula\Core\Core.Infra\",
            @"D:\EngineSource\Nebula\Engine\Nebula\Core\Core.Debugger\",
            @"D:\EngineSource\Nebula\Engine\Nebula\Engine\Engine\",
        });  
        
        module.Defines.AddRange(new string[]
        {
            
        });
        
        module.Headers.AddRange(new string[]
        {
            @"EngineCommon.h",
            @"Debugger\LoggerAPI.h"
        });
        
        // lib
        module.LibraryDirs.AddRange(new string[]
        {
            @"D:\EngineSource\Nebula\Engine\Nebula\x64\Debug"
        });
        
        module.Libraries.AddRange(new string[]
        {
            @"Engine.lib"
        });
    }
    
    public void Setup(Driver driver)
    {
        var options = driver.Options;
        options.GeneratorKind = GeneratorKind.CSharp;
        SetupDebuggerModule(options);
    }

    #endregion
    
    public void Preprocess(Driver driver, ASTContext ctx)
    {
        // throw new NotImplementedException();
    }

    public void Postprocess(Driver driver, ASTContext ctx)
    {
        // throw new NotImplementedException();
    }
    
    public void SetupPasses(Driver driver)
    {
        // throw new NotImplementedException();
    }
}