using System;
using ArisenBinding.Arisen.Core;

namespace ArisenEngine.Core.Lifecycle;

public static class Bootstrap
{
    private static bool m_IsInitialized = false;

    public static bool Initialize()
    {
        if (m_IsInitialized) return true;

        try
        {
            // Call native EngineInit::Initialize generated by CppSharp
            if (EngineInit.Initialize())
            {
                m_IsInitialized = true;
                return true;
            }
        }
        catch (Exception e)
        {
            // Fallback to console if logger is not ready, but usually EngineInit handles logger
            Console.WriteLine($"[Bootstrap] Failed to initialize native engine: {e.Message}");
        }

        return false;
    }

    public static void Shutdown()
    {
        if (!m_IsInitialized) return;

        try
        {
            EngineInit.Shutdown();
            m_IsInitialized = false;
        }
        catch (Exception e)
        {
            Console.WriteLine($"[Bootstrap] Error during native engine shutdown: {e.Message}");
        }
    }
}
