<?xml version='1.0' encoding='utf-8'?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <BaseOutputPath>..\x64\</BaseOutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <PlatformTarget>x64</PlatformTarget>
    <RootNamespace>ArisenEngine</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <None Update="**\package.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AutoBinding\AutoBinding.csproj" />
    <ProjectReference Include="..\Serialization\Serialization\Serialization.csproj" />
    <ProjectReference Include="..\External\ArisenDAG\ArisenDAG.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ArisenEditor" />
    <InternalsVisibleTo Include="ArisenEditor.Desktop" />
  </ItemGroup>

  
  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>ArisenEditor</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
<PropertyGroup Condition="'$(Configuration)' == 'Debug'"><OutputPath>..\Projects\VisualStudio\CSharpEngineTest\Outputs\Debug\</OutputPath></PropertyGroup><PropertyGroup Condition="'$(Configuration)' == 'Release'"><OutputPath>..\Projects\VisualStudio\CSharpEngineTest\Outputs\Release\</OutputPath></PropertyGroup></Project>