// ----------------------------------------------------------------------------
// <auto-generated>
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
// </auto-generated>
// ----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;
using __CallingConvention = global::System.Runtime.InteropServices.CallingConvention;
using __IntPtr = global::System.IntPtr;

#pragma warning disable CS0109 // Member does not hide an inherited member; new keyword is not required

namespace ArisenBinding.NativePlatform
{
    namespace ArisenEngine
    {
        namespace Platforms
        {
            public unsafe partial class ShaderCompilerOutput : IDisposable
            {
                [StructLayout(LayoutKind.Sequential, Size = 48)]
                public partial struct __Internal
                {
                    internal __IntPtr codePointer;
                    internal ulong codeSize;
                    internal global::Std.BasicString.__Internalc__N_std_S_basic_string__C___N_std_S_char_traits__C___N_std_S_allocator__C msgOut;

                    [SuppressUnmanagedCodeSecurity, DllImport("Core.Platform.dll", EntryPoint = "??0ShaderCompilerOutput@Platforms@ArisenEngine@@QEAA@AEBU012@@Z", CallingConvention = __CallingConvention.Cdecl)]
                    internal static extern __IntPtr cctor(__IntPtr __instance, __IntPtr _0);

                    [SuppressUnmanagedCodeSecurity, DllImport("Core.Platform.dll", EntryPoint = "??0ShaderCompilerOutput@Platforms@ArisenEngine@@QEAA@XZ", CallingConvention = __CallingConvention.Cdecl)]
                    internal static extern __IntPtr ctor(__IntPtr __instance);

                    [SuppressUnmanagedCodeSecurity, DllImport("Core.Platform.dll", EntryPoint = "??1ShaderCompilerOutput@Platforms@ArisenEngine@@QEAA@XZ", CallingConvention = __CallingConvention.Cdecl)]
                    internal static extern void dtor(__IntPtr __instance);
                }

                public __IntPtr __Instance { get; protected set; }

                internal static readonly new global::System.Collections.Concurrent.ConcurrentDictionary<IntPtr, global::ArisenBinding.NativePlatform.ArisenEngine.Platforms.ShaderCompilerOutput> NativeToManagedMap =
                    new global::System.Collections.Concurrent.ConcurrentDictionary<IntPtr, global::ArisenBinding.NativePlatform.ArisenEngine.Platforms.ShaderCompilerOutput>();

                internal static void __RecordNativeToManagedMapping(IntPtr native, global::ArisenBinding.NativePlatform.ArisenEngine.Platforms.ShaderCompilerOutput managed)
                {
                    NativeToManagedMap[native] = managed;
                }

                internal static bool __TryGetNativeToManagedMapping(IntPtr native, out global::ArisenBinding.NativePlatform.ArisenEngine.Platforms.ShaderCompilerOutput managed)
                {
    
                    return NativeToManagedMap.TryGetValue(native, out managed);
                }

                protected bool __ownsNativeInstance;

                internal static ShaderCompilerOutput __CreateInstance(__IntPtr native, bool skipVTables = false)
                {
                    if (native == __IntPtr.Zero)
                        return null;
                    return new ShaderCompilerOutput(native.ToPointer(), skipVTables);
                }

                internal static ShaderCompilerOutput __GetOrCreateInstance(__IntPtr native, bool saveInstance = false, bool skipVTables = false)
                {
                    if (native == __IntPtr.Zero)
                        return null;
                    if (__TryGetNativeToManagedMapping(native, out var managed))
                        return (ShaderCompilerOutput)managed;
                    var result = __CreateInstance(native, skipVTables);
                    if (saveInstance)
                        __RecordNativeToManagedMapping(native, result);
                    return result;
                }

                internal static ShaderCompilerOutput __CreateInstance(__Internal native, bool skipVTables = false)
                {
                    return new ShaderCompilerOutput(native, skipVTables);
                }

                private static void* __CopyValue(__Internal native)
                {
                    var ret = Marshal.AllocHGlobal(sizeof(__Internal));
                    global::ArisenBinding.NativePlatform.ArisenEngine.Platforms.ShaderCompilerOutput.__Internal.cctor(ret, new __IntPtr(&native));
                    return ret.ToPointer();
                }

                private ShaderCompilerOutput(__Internal native, bool skipVTables = false)
                    : this(__CopyValue(native), skipVTables)
                {
                    __ownsNativeInstance = true;
                    __RecordNativeToManagedMapping(__Instance, this);
                }

                protected ShaderCompilerOutput(void* native, bool skipVTables = false)
                {
                    if (native == null)
                        return;
                    __Instance = new __IntPtr(native);
                }

                public ShaderCompilerOutput(global::ArisenBinding.NativePlatform.ArisenEngine.Platforms.ShaderCompilerOutput _0)
                {
                    __Instance = Marshal.AllocHGlobal(sizeof(global::ArisenBinding.NativePlatform.ArisenEngine.Platforms.ShaderCompilerOutput.__Internal));
                    __ownsNativeInstance = true;
                    __RecordNativeToManagedMapping(__Instance, this);
                    if (ReferenceEquals(_0, null))
                        throw new global::System.ArgumentNullException("_0", "Cannot be null because it is a C++ reference (&).");
                    var __arg0 = _0.__Instance;
                    __Internal.cctor(__Instance, __arg0);
                }

                public ShaderCompilerOutput()
                {
                    __Instance = Marshal.AllocHGlobal(sizeof(global::ArisenBinding.NativePlatform.ArisenEngine.Platforms.ShaderCompilerOutput.__Internal));
                    __ownsNativeInstance = true;
                    __RecordNativeToManagedMapping(__Instance, this);
                    __Internal.ctor(__Instance);
                }

                public void Dispose()
                {
                    Dispose(disposing: true, callNativeDtor : __ownsNativeInstance );
                }

                partial void DisposePartial(bool disposing);

                internal protected virtual void Dispose(bool disposing, bool callNativeDtor )
                {
                    if (__Instance == IntPtr.Zero)
                        return;
                    NativeToManagedMap.TryRemove(__Instance, out _);
                    DisposePartial(disposing);
                    if (callNativeDtor)
                        __Internal.dtor(__Instance);
                    if (__ownsNativeInstance)
                        Marshal.FreeHGlobal(__Instance);
                    __Instance = IntPtr.Zero;
                }

                public __IntPtr CodePointer
                {
                    get
                    {
                        return ((__Internal*)__Instance)->codePointer;
                    }

                    set
                    {
                        ((__Internal*)__Instance)->codePointer = (__IntPtr) value;
                    }
                }

                public ulong CodeSize
                {
                    get
                    {
                        return ((__Internal*)__Instance)->codeSize;
                    }

                    set
                    {
                        ((__Internal*)__Instance)->codeSize = value;
                    }
                }
            }

            public unsafe partial class ShaderCompileParams : IDisposable
            {
                [StructLayout(LayoutKind.Sequential, Size = 296)]
                public partial struct __Internal
                {
                    internal global::Std.BasicString.__Internalc__N_std_S_basic_string__W___N_std_S_char_traits__W___N_std_S_allocator__W input;
                    internal global::Std.BasicString.__Internalc__N_std_S_basic_string__W___N_std_S_char_traits__W___N_std_S_allocator__W entry;
                    internal global::Std.BasicString.__Internalc__N_std_S_basic_string__W___N_std_S_char_traits__W___N_std_S_allocator__W shaderModel;
                    internal global::Std.BasicString.__Internalc__N_std_S_basic_string__W___N_std_S_char_traits__W___N_std_S_allocator__W target;
                    internal global::Std.BasicString.__Internalc__N_std_S_basic_string__W___N_std_S_char_traits__W___N_std_S_allocator__W targetEnv;
                    internal global::Std.BasicString.__Internalc__N_std_S_basic_string__W___N_std_S_char_traits__W___N_std_S_allocator__W optimizeLevel;
                    internal global::ArisenBinding.NativePlatform.ArisenEngine.RHI.ProgramStage stage;
                    internal global::Std.Vector.__Internalc__N_std_S_vector____N_std_S_basic_string__W___N_std_S_char_traits__W___N_std_S_allocator__W___N_std_S_allocator__S0_ defines;
                    internal global::Std.Vector.__Internalc__N_std_S_vector____N_std_S_basic_string__W___N_std_S_char_traits__W___N_std_S_allocator__W___N_std_S_allocator__S0_ includes;
                    internal global::Std.Optional.__Internal output;
                    internal global::Std.Optional.__Internal useDXLayout;

                    [SuppressUnmanagedCodeSecurity, DllImport("Core.Platform.dll", EntryPoint = "??0ShaderCompileParams@Platforms@ArisenEngine@@QEAA@AEBU012@@Z", CallingConvention = __CallingConvention.Cdecl)]
                    internal static extern __IntPtr cctor(__IntPtr __instance, __IntPtr _0);

                    [SuppressUnmanagedCodeSecurity, DllImport("Core.Platform.dll", EntryPoint = "??0ShaderCompileParams@Platforms@ArisenEngine@@QEAA@XZ", CallingConvention = __CallingConvention.Cdecl)]
                    internal static extern __IntPtr ctor(__IntPtr __instance);

                    [SuppressUnmanagedCodeSecurity, DllImport("Core.Platform.dll", EntryPoint = "??1ShaderCompileParams@Platforms@ArisenEngine@@QEAA@XZ", CallingConvention = __CallingConvention.Cdecl)]
                    internal static extern void dtor(__IntPtr __instance);
                }

                public __IntPtr __Instance { get; protected set; }

                internal static readonly new global::System.Collections.Concurrent.ConcurrentDictionary<IntPtr, global::ArisenBinding.NativePlatform.ArisenEngine.Platforms.ShaderCompileParams> NativeToManagedMap =
                    new global::System.Collections.Concurrent.ConcurrentDictionary<IntPtr, global::ArisenBinding.NativePlatform.ArisenEngine.Platforms.ShaderCompileParams>();

                internal static void __RecordNativeToManagedMapping(IntPtr native, global::ArisenBinding.NativePlatform.ArisenEngine.Platforms.ShaderCompileParams managed)
                {
                    NativeToManagedMap[native] = managed;
                }

                internal static bool __TryGetNativeToManagedMapping(IntPtr native, out global::ArisenBinding.NativePlatform.ArisenEngine.Platforms.ShaderCompileParams managed)
                {
    
                    return NativeToManagedMap.TryGetValue(native, out managed);
                }

                protected bool __ownsNativeInstance;

                internal static ShaderCompileParams __CreateInstance(__IntPtr native, bool skipVTables = false)
                {
                    if (native == __IntPtr.Zero)
                        return null;
                    return new ShaderCompileParams(native.ToPointer(), skipVTables);
                }

                internal static ShaderCompileParams __GetOrCreateInstance(__IntPtr native, bool saveInstance = false, bool skipVTables = false)
                {
                    if (native == __IntPtr.Zero)
                        return null;
                    if (__TryGetNativeToManagedMapping(native, out var managed))
                        return (ShaderCompileParams)managed;
                    var result = __CreateInstance(native, skipVTables);
                    if (saveInstance)
                        __RecordNativeToManagedMapping(native, result);
                    return result;
                }

                internal static ShaderCompileParams __CreateInstance(__Internal native, bool skipVTables = false)
                {
                    return new ShaderCompileParams(native, skipVTables);
                }

                private static void* __CopyValue(__Internal native)
                {
                    var ret = Marshal.AllocHGlobal(sizeof(__Internal));
                    global::ArisenBinding.NativePlatform.ArisenEngine.Platforms.ShaderCompileParams.__Internal.cctor(ret, new __IntPtr(&native));
                    return ret.ToPointer();
                }

                private ShaderCompileParams(__Internal native, bool skipVTables = false)
                    : this(__CopyValue(native), skipVTables)
                {
                    __ownsNativeInstance = true;
                    __RecordNativeToManagedMapping(__Instance, this);
                }

                protected ShaderCompileParams(void* native, bool skipVTables = false)
                {
                    if (native == null)
                        return;
                    __Instance = new __IntPtr(native);
                }

                public ShaderCompileParams(global::ArisenBinding.NativePlatform.ArisenEngine.Platforms.ShaderCompileParams _0)
                {
                    __Instance = Marshal.AllocHGlobal(sizeof(global::ArisenBinding.NativePlatform.ArisenEngine.Platforms.ShaderCompileParams.__Internal));
                    __ownsNativeInstance = true;
                    __RecordNativeToManagedMapping(__Instance, this);
                    if (ReferenceEquals(_0, null))
                        throw new global::System.ArgumentNullException("_0", "Cannot be null because it is a C++ reference (&).");
                    var __arg0 = _0.__Instance;
                    __Internal.cctor(__Instance, __arg0);
                }

                public ShaderCompileParams()
                {
                    __Instance = Marshal.AllocHGlobal(sizeof(global::ArisenBinding.NativePlatform.ArisenEngine.Platforms.ShaderCompileParams.__Internal));
                    __ownsNativeInstance = true;
                    __RecordNativeToManagedMapping(__Instance, this);
                    __Internal.ctor(__Instance);
                }

                public void Dispose()
                {
                    Dispose(disposing: true, callNativeDtor : __ownsNativeInstance );
                }

                partial void DisposePartial(bool disposing);

                internal protected virtual void Dispose(bool disposing, bool callNativeDtor )
                {
                    if (__Instance == IntPtr.Zero)
                        return;
                    NativeToManagedMap.TryRemove(__Instance, out _);
                    DisposePartial(disposing);
                    if (callNativeDtor)
                        __Internal.dtor(__Instance);
                    if (__ownsNativeInstance)
                        Marshal.FreeHGlobal(__Instance);
                    __Instance = IntPtr.Zero;
                }

                public global::ArisenBinding.NativePlatform.ArisenEngine.RHI.ProgramStage Stage
                {
                    get
                    {
                        return ((__Internal*)__Instance)->stage;
                    }

                    set
                    {
                        ((__Internal*)__Instance)->stage = value;
                    }
                }
            }

            public unsafe partial class ShaderCompilerAPI
            {
                public partial struct __Internal
                {
                    [SuppressUnmanagedCodeSecurity, DllImport("Core.Platform.dll", EntryPoint = "InitDXC", CallingConvention = __CallingConvention.Cdecl)]
                    internal static extern void InitDXC();

                    [SuppressUnmanagedCodeSecurity, DllImport("Core.Platform.dll", EntryPoint = "ReleaseDXC", CallingConvention = __CallingConvention.Cdecl)]
                    internal static extern void ReleaseDXC();

                    [SuppressUnmanagedCodeSecurity, DllImport("Core.Platform.dll", EntryPoint = "CompileShaderFromFile", CallingConvention = __CallingConvention.Cdecl)]
                    [return: MarshalAs(UnmanagedType.I1)]
                    internal static extern bool CompileShaderFromFile(__IntPtr @params, __IntPtr output);
                }

                public static void InitDXC()
                {
                    __Internal.InitDXC();
                }

                public static void ReleaseDXC()
                {
                    __Internal.ReleaseDXC();
                }

                public static bool CompileShaderFromFile(global::ArisenBinding.NativePlatform.ArisenEngine.Platforms.ShaderCompileParams @params, global::ArisenBinding.NativePlatform.ArisenEngine.Platforms.ShaderCompilerOutput output)
                {
                    if (ReferenceEquals(@params, null))
                        throw new global::System.ArgumentNullException("@params", "Cannot be null because it is a C++ reference (&).");
                    var __arg0 = @params.__Instance;
                    if (ReferenceEquals(output, null))
                        throw new global::System.ArgumentNullException("output", "Cannot be null because it is a C++ reference (&).");
                    var __arg1 = output.__Instance;
                    var ___ret = __Internal.CompileShaderFromFile(__arg0, __arg1);
                    return ___ret;
                }
            }
        }
    }
}
